apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting
  template:
    metadata:
      labels:
        app: accounting 
    spec:
      containers:
      - name: accounting
        image: moonorb/accounting:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
        env:
        - name: REGISTRATION_SERVER_HOSTNAME
          value: registration.microservice-demo.svc.cluster.local
        - name: _JAVA_OPTIONS
          value: -Deureka.instance.hostName=accounting


