apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration
        image: moonorb/registration:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 1111

